### ISSUE TITLE
Can't find library rt on Mac

### ISSUE THREAD

**Issue by kshehata** [OpenMined/PIR#1]
Hey Bogden, figured we could use the tools in github rather than Slack so that we can't search this afterwards. Compiling the starting point on Mac produces this error:

`ld: library not found for -lrt`

Looks like the rt library isn't available on Mac, but also isn't needed. I just commented that line out of the build file and then everything worked. Not sure what the right answer is, but there's got to be a way in Bazel to only include rt if it's needed.

**Comment by bcebere** [comment]
It was needed for an older glibc version for Linux.

I will drop it for now, until it's actually needed.
