### ISSUE TITLE
Warnings during compilation

### ISSUE THREAD

**Issue by tlepoint** [OpenMined/PIR#12]
## Description
There are two warnings during compilations.

## How to Reproduce
1. `bazel build -c opt //pir/cpp/...`

## Expected Behavior
No warning

## Screenshots
NA

## System Information
 - OS: macOS
 - OS Version: 10.15

## Additional Context

```
pir/cpp/utils.h:33:21: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
   33 |   for (int i = 1; i < sizeof(n) * 8; i = i << 1) {
      |                   ~~^~~~~~~~~~~~~~~
```
and
```
pir/cpp/server_test.cpp:122:16: warning: unused variable 'desired_index' [-Wunused-variable]
  122 |   const size_t desired_index = 7;
      |                ^~~~~~~~~~~~~
```

**Comment by bcebere** [comment]
Fixed.
Also, added more CI checks to prevent this kind of issues.
